version: "3.9"
services: 
  client:
    image: client
    build:
      context: ./client
    container_name: client
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - API_URL=http://server:3001
    depends_on:
      - server
  server:
    image: server
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"
    restart: unless-stopped
